## Leet 471 problem. 

Given a non-empty string, encode the string such that its encoded length is the shortest.

The encoding rule is: k[encoded_string], where the encoded_string inside the square brackets is being repeated exactly k times.

Note: k will be a positive integer and encoded string will not be empty or have extra space. You may assume that the input string contains only lowercase English letters. The string's length is at most 160. If an encoding process does not make the string shorter, then do not encode it. If there are several solutions, return any of them is fine.

> __Example 1:__
>
> Input: "aaa"
> 
> Output: "aaa"
> 
> Explanation: There is no way to encode it such that it is shorter than the input string, so we do not encode it.
>
>\\
> __Example 2:__
> 
> Input: "aaaaa"
> 
> Output: "5[a]"
> 
> Explanation: "5[a]" is shorter than "aaaaa" by 1 character.
>
>\\
> __Example 3:__
> 
> Input: "aaaaaaaaaa"
>
> Output: "10[a]"
>
> Explanation: "a9[a]" or "9[a]a" are also valid solutions, both of them have the same length = 5, which is the same as "10[a]".
>
>\\
> __Example 4:__
> 
> Input: "aabcaabcd"
>
> Output: "2[aabc]d"
>
> Explanation: "aabc" occurs twice, so one answer can be "2[aabc]d".
> 
>\\
>
> __Example 5:__
> Input: "abbbabbbcabbbabbbc"
>
> Output: "2[2[abbb]c]"
>
> Explanation: "abbbabbbc" occurs twice, but "abbbabbbc" can also be encoded to "2[abbb]c", so one answer can be "2[2[abbb]c]".


In [8]:
import math

class EncodedString:
  def __init__(self, enc_str, count, start):
    self.enc_str = enc_str
    self.count = count
    self.start = start
    self.end = start + len(enc_str) 
    self.encode = len(str(self.count))+len(self.enc_str) + 2 < self.end - self.start

  def __repr__(self):
    return "[{}]{} {} - {} --{}--".format(self.count, self.enc_str, self.start, self.end, self.encode)
  
  def incr_count(self):
    self.count += 1
    self.end = self.end + len(self.enc_str)
    self.encode = len(str(self.count))+len(self.enc_str) + 2 < self.end - self.start

  def is_encoding_better(self):
    return self.encode
  
  def len_source_string(self):
    return self.end - self.start
  
  def len_encoded_string(self):
    return len(self.enc_str)+len(str(self.count)) + 2
  
  def encode_string(self, input_string):
    return input_string[:self.start] + "[{}]{}".format(self.count, self.enc_str) + input_string[self.end:]

  def is_overlapping(self, encoded_str):
    if self.start < encoded_str.end and self.end > encoded_str.start:
      return True
    else:
      return False
  
def find_sequences(input_str):
  input_sequence = list()
  seq_count = 1
  enc_seq_str = ''
  enc_seq_str_pos = (0, 0)
  encoded_string = None
  prior_str = ''
  post_str = ''
  for incr in range(1,len(input_str)//2+1):
    # print("-----{}-----".format(incr))
    seq_str = list()
    j = 0
    while j < len(input_str):
      # print("j - {}, incr - {}".format(j, incr))
      k = j+incr
      if k+incr > len(input_str):
        if seq_count > 1:
          post_str = input_str[j+incr:]
          # input_sequence.append("{}{}[{}]{}".format(prior_str,seq_count, enc_seq_str, post_str))
          if (encoded_string.is_encoding_better()):
            input_sequence.append(encoded_string)
          print(encoded_string)
          print(encoded_string.is_encoding_better())
          # print("{} - {} - {}".format(prior_str, enc_seq_str, post_str))
          seq_count = 1
          enc_seq_str = ''
        j += 1
        break
      if input_str[j:j+incr] == input_str[k:k+incr]:
        # print("{} == {}".format(input_str[j:j+incr], input_str[k:k+incr]))
        if seq_count == 1:
          prior_str = input_str[:j]
          encoded_string = EncodedString(input_str[j:j+incr],seq_count,j)
          # print("prior_str - {}".format(prior_str))
        seq_count += 1
        encoded_string.incr_count()
        enc_seq_str = input_str[j:j+incr]
        j += incr
      elif seq_count > 1:
        post_str = input_str[j+incr:]
        # print("{} - {} - {}".format(prior_str, enc_seq_str, post_str))
        # input_sequence.append("{}{}[{}]{}".format(prior_str,seq_count, enc_seq_str, post_str))
        if (encoded_string.is_encoding_better()):
          input_sequence.append(encoded_string)
        print(encoded_string)
        print(encoded_string.is_encoding_better())
        seq_count = 1
        enc_seq_str = ''
        j += 1 
      else:
        # print("NO MATCH")
        j += 1 
        continue
        
  return input_sequence      

input_str = "aabcbcaaaaaaabaab"
print(input_str)
print("Sequences found are:")
encoded_seq = find_sequences(input_str)

aabcbcaaaaaaabaab
Sequences found are:
[2]a 0 - 2 --False--
False
[7]a 6 - 13 --True--
True
[2]a 14 - 16 --False--
False
[2]bc 2 - 6 --False--
False
[3]aa 6 - 12 --True--
True
[2]aaa 6 - 12 --False--
False
[2]aab 11 - 17 --False--
False


In [14]:
from functools import cmp_to_key

def compare_enc_pos(enc_str1, enc_str2):
  if enc_str1.start < enc_str2.start:
    return -1
  elif enc_str1.start > enc_str2.start:
    return 1
  else:
    if enc_str1.end < enc_str2.end:
      return -1
    elif enc_str1.end > enc_str2.end:
      return 1
    else:
      if len(enc_str1.enc_str) < len(enc_str2.enc_str):
        return -1
      elif len(enc_str1.enc_str) > len(enc_str2.enc_str):
        return 1
      else:
        return 0


def get_next_str(curr_str, curr_pos):
  if (curr_pos >= len(input_string)):
    return ''
  
  if len(encoding_list) == 0:
    return curr_str + input_string[curr_pos:]
  
  enc_str = encoding_list.pop()
  if curr_pos < enc_str.start:
    curr_str = curr_str + input_string[curr_pos:enc_str.start]
    curr_pos = enc_str.start
  
  if curr_pos == enc_str.start:
    temp_str1 = curr_str + "[{}]{}".format(enc_str.count, enc_str.enc_str)
    str1 = get_next_str(temp_str1, enc_str.end)

    temp_str2 = curr_str + input_string[enc_str.start:enc_str.end]
    str2 = get_next_str(temp_str2, enc_str.end)

    if (len(temp_str1) < len(temp_str2)):
      return temp_str1
    else:
      return temp_str2
  

compare_enc_pos_key = cmp_to_key(compare_enc_pos)


input_string = "aaabcbcbcaaaaaaaab"
encoding_list = find_sequences(input_string)
print(encoding_list)
encoding_list = sorted(encoding_list,key=compare_enc_pos_key)
print(encoding_list)
curr_pos = 0
curr_str = ''

[3]a 0 - 3 --False--
False
[8]a 9 - 17 --True--
True
[3]bc 3 - 9 --True--
True
[4]aa 9 - 17 --True--
True
[2]aaa 9 - 15 --False--
False
[2]aaaa 9 - 17 --True--
True
[[8]a 9 - 17 --True--, [3]bc 3 - 9 --True--, [4]aa 9 - 17 --True--, [2]aaaa 9 - 17 --True--]
[[3]bc 3 - 9 --True--, [8]a 9 - 17 --True--, [4]aa 9 - 17 --True--, [2]aaaa 9 - 17 --True--]


In [12]:
print("012345678901234567890123456789")
print(input_str)
x = encoded_seq[0]
print(x)
y = encoded_seq[1]
print(y)
print(x.is_overlapping(y))
print(x.len_source_string())
print(y.len_source_string())

print(x.encode_string(input_str))

012345678901234567890123456789
aabcbcaaaaaaabaab
[7]a 6 - 13 --True--
[3]aa 6 - 12 --True--
True
7
6
aabcbc[7]abaab


In [29]:
import numpy as np
from itertools import permutations

input_string = "aaaaaabcbcbcaab"
encoding_list = find_sequences(input_string)

def create_candidate_string(input_string, encoding_list):
  new_candidate_string = list()
  pair_matrix = np.ones([len(encoding_list), len(encoding_list)])
  print(pair_matrix)
  for pair in permutations(range(len(encoding_list)), 2):
    print(pair)
    if encoding_list[pair[0]].is_overlapping(encoding_list[pair[1]]):
      pair_matrix[pair[0],pair[1]] = 0
  
  for i in range(len(encoding_list)):
    temp_string = input_string
    print(temp_string)
    for j in range(len(encoding_list)):
      if pair_matrix[i,j] == 1:
        temp_enc_string = encoding_list[j]
        temp_string = temp_enc_string.encode_string(temp_string)
    if (temp_string not in new_candidate_string):
      new_candidate_string.append(temp_string)
  return new_candidate_string

  print(pair_matrix)
create_candidate_string(input_string, encoding_list)

[6]a 0 - 6 --True--
True
[2]a 12 - 14 --False--
False
[3]aa 0 - 6 --True--
True
[3]bc 6 - 12 --True--
True
[2]aaa 0 - 6 --False--
False
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(0, 1)
(0, 2)
(1, 0)
(1, 2)
(2, 0)
(2, 1)
aaaaaabcbcbcaab
aaaaaabcbcbcaab
aaaaaabcbcbcaab


['[6]abc[3]bcb', '[3]aab[3]bcab', '[3]aab[3]bc']